/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author vector
 */
public class Visualiser extends javax.swing.JFrame {

    En en;

    /**
     * Creates new form Visualiser
     */
    public Visualiser() {
        initComponents();
    }

    public Visualiser(En en) {
        this();
        this.en = en;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Visualiser");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jLabel1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualiser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Visualiser a = new Visualiser();
//                
//                System.out.println("ddddddddddddd");
//                a.r = new ArrayList<>();
//                a.r.add("aaa");
//                a.r.add("aaa");
//                a.r.add("aaa");
//                a.d = new ArrayList<>();
//                ArrayList<Double> c = new ArrayList<>();
//                c.add(new Double(1));
//                c.add(new Double(2));
//                c.add(new Double(3));
//                a.d.add(c);
//                c = new ArrayList<>();
//                c.add(new Double(4));
//                c.add(new Double(5));
//                c.add(new Double(6));
//                a.d.add(c);
//                c = new ArrayList<>();
//                c.add(new Double(4));
//                c.add(new Double(5));
//                c.add(new Double(6));
//                a.d.add(c);
//                c = new ArrayList<>();
//                c.add(new Double(4));
//                c.add(new Double(5));
//                c.add(new Double(6));
//                a.d.add(c);
//                a.jPanel1.removeAll();
//                MonModel mc=new MonModel();
//                JTable j=new JTable(mc);
//                JScrollPane ss = new JScrollPane(j);
//                a.jPanel1.add(ss);
//                a.pack();
                a.setVisible(true);
            }
        });
    }

    public static class MonModel extends AbstractTableModel {
        
        Data d;

        public MonModel(Data d) {
            this.d = d;
        }

        @Override
        public String getColumnName(int column) {
            if(!d.names.isEmpty()){
                return d.names.get(column);
            }
            return super.getColumnName(column);
        }
        
        @Override
        public int getColumnCount() {
            System.out.println("Visualiser : Col = "+d.lines.get(0).size());
            return d.lines.get(0).size();
        }

        @Override
        public int getRowCount() {
            return d.lines.size();//l is the arraylist that contains the 3 elements
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            return d.lines.get(rowIndex).get(columnIndex);
        }
    }
//
//    ArrayList<String> r;
//    ArrayList<ArrayList<Double>> d;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
